export const API_ERRORS = {
  BAD_REQUEST: "Invalid request. Please check your inputs and try again.",
  UNAUTHORIZED: "Invalid access key or unauthorized request.",
  FORBIDDEN: "You don't have permission to perform this action.",
  NOT_FOUND: "The requested resource could not be found.",
  METHOD_NOT_ALLOWED: "This method is not allowed.",
  GONE: "This resource is no longer available.",
  PAYLOAD_TOO_LARGE: "The uploaded file exceeds the allowed size limit.",
  UNSUPPORTED_MEDIA_TYPE: "This file type is not supported.",
  TOO_MANY_REQUESTS: "You are doing that too fast. Please slow down and try again.",
  INTERNAL_SERVER_ERROR: "An unexpected internal server error occurred.",
  NOT_IMPLEMENTED: "This feature is not implemented yet.",
  BAD_GATEWAY: "Bad gateway. Please try again later.",
  SERVICE_UNAVAILABLE: "The service is temporarily unavailable.",
  GATEWAY_TIMEOUT: "The request timed out. Please try again.",
} as const;
