export const SITE_URL = "https://hypastack.com"
export const SITE_NAME = "Hypastack"
export const SITE_TAGLINE = "Share files privately, worldwide"
export const SITE_DESCRIPTION = "Share files privately or host images on a fast global CDN. Encrypted in your browser, no email, no ads, no tracking. Free, source-available, EU-based."
export const SITE_KEYWORDS = "private file sharing, encrypted file sharing, burn after reading, free CDN, image hosting, source-available, EU file hosting, pastebin alternative"
export const ICON_URL = "https://r2.hypastack.com/cdn/hypaasset/hypastack.webp"
export const PREVIEW_URL = "https://r2.hypastack.com/cdn/wpoxysqdixzy/preview-main.png"
