export const SITE_URL = "https://hypastack.com"
export const SITE_NAME = "Hypastack"
export const SITE_TAGLINE = "Private File Sharing & Global CDN"
export const SITE_DESCRIPTION = "Private, ad-free file sharing & global CDN with no tracking or logs, no personal data collected, EU-based servers, free-to-use, and 100% open-source."
export const SITE_KEYWORDS = "file sharing, file hosting, CDN hosting, free file sharing, private file sharing, anonymous file sharing, no tracking file sharing, open source file sharing, EU file hosting, ad-free file hosting, free file upload, public CDN, Hypastack, Dropbox alternative, WeTransfer alternative, Wormhole alternative, Google Drive alternative, file transfer, send large files, share files online, temporary file hosting, burn after reading, permanent CDN, free CDN, file sharing no account, upload files online, fast file sharing, secure file sharing, private CDN, no ads file sharing, no login file sharing, no signup file sharing"
export const ICON_URL = "https://r2.hypastack.com/cdn/zvo7jefzshuu/logo-main.webp"
export const FAVICON_URL = "https://r2.hypastack.com/cdn/7byi0fl52s1c/favicon.webp"
export const PREVIEW_URL = "https://r2.hypastack.com/cdn/wpoxysqdixzy/preview-main.png"
