// Subsets Material Symbols Rounded to just the icons this codebase uses. The
// full variable font is 5.3 MB and was shipped to every visitor; the subset is
// a few KB. Runs automatically before `next build` (see package.json) and can
// be run by hand after adding icons: `node scripts/subset-icons.mjs`.
//
// Ligature rendering can't be subset (the letters a-z reach every icon's
// ligature, so harfbuzz keeps all ~4000 glyphs). Instead each icon's private-
// use codepoint is kept and MIcon renders that character via the generated
// constants/icon-codepoints.ts map. The variable axes are also instanced to
// the values globals.css pins (FILL 1, wght 700, GRAD 200, opsz 24).
//
// How it finds icons: every string literal in app/, components/, lib/, hooks/
// and constants/ is intersected with the official codepoints list, so dynamic
// maps (e.g. file-type -> icon) are covered as long as names appear as
// literals somewhere. Over-capturing a common word that happens to be an icon
// name only costs a few bytes.

import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "fs"
import { join, dirname } from "path"
import { fileURLToPath } from "url"
import subsetFont from "subset-font"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")

// name -> codepoint (hex) for every icon, from Google's codepoints file
const codepoints = new Map(
  readFileSync(join(root, "scripts/material-symbols-rounded.codepoints"), "utf8")
    .trim()
    .split("\n")
    .map((l) => l.trim().split(" "))
)

const sourceFiles = []
function walk(dir) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name)
    if (e.isDirectory()) walk(p)
    else if (/\.tsx?$/.test(e.name)) sourceFiles.push(p)
  }
}
for (const d of ["app", "components", "lib", "hooks", "constants"]) walk(join(root, d))

const used = new Set()
for (const f of sourceFiles) {
  if (f.endsWith("icon-codepoints.ts")) continue // the generated map itself
  for (const m of readFileSync(f, "utf8").matchAll(/["'`]([a-z][a-z0-9_]{1,40})["'`]/g)) {
    if (codepoints.has(m[1])) used.add(m[1])
  }
}

const names = [...used].sort()
const chars = names.map((n) => String.fromCodePoint(parseInt(codepoints.get(n), 16))).join("")

const fullFont = readFileSync(join(root, "node_modules/material-symbols/material-symbols-rounded.woff2"))
const subset = await subsetFont(fullFont, chars, {
  targetFormat: "woff2",
  // Instance the axes to what globals.css pins so the static glyphs match.
  variationAxes: { FILL: 1, wght: 700, GRAD: 200, opsz: 24 },
})

mkdirSync(join(root, "public/fonts"), { recursive: true })
writeFileSync(join(root, "public/fonts/material-symbols-rounded-subset.woff2"), subset)

const map = names.map((n) => `  ${n.includes("-") ? `"${n}"` : n}: "\\u{${codepoints.get(n)}}",`).join("\n")
writeFileSync(
  join(root, "constants/icon-codepoints.ts"),
  `// GENERATED by scripts/subset-icons.mjs — do not edit by hand.
// Maps every Material Symbols icon name used in the codebase to its codepoint
// in public/fonts/material-symbols-rounded-subset.woff2. After using a new
// icon, re-run: node scripts/subset-icons.mjs (also runs on every build).

export const ICON_CODEPOINTS: Record<string, string> = {
${map}
}
`
)

console.log(`[icons] subset ${names.length} icons: ${(fullFont.length / 1024 / 1024).toFixed(1)} MB -> ${(subset.length / 1024).toFixed(1)} KB`)
