name: Deploy Hypastack

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '**/*.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SSH_PORT }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            export XDG_RUNTIME_DIR=/run/user/$(id -u)
            cd ~/Hypastack-Open-Source
            git fetch origin
            git reset --hard origin/main
            podman build --network=host -t localhost/hypastack:latest .
            systemctl --user restart hypastack.service
            podman image prune -f
